# Generated by Django 3.1.7 on 2021-06-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0012_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
