# Generated by Django 3.1.7 on 2021-06-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0016_replie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/user.png', upload_to='images'),
        ),
    ]
