# Generated by Django 3.1.7 on 2021-06-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0017_auto_20210621_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/images/user.png', upload_to='images'),
        ),
    ]
