# Generated by Django 5.0.1 on 2024-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0021_rename_image_profile_avatar_profile_plant_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plant_image_1',
            field=models.ImageField(default='default/user.png', upload_to='additional_images'),
        ),
    ]
