# Generated by Django 3.1.7 on 2021-06-18 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_of_user', '0004_remove_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user1',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
