# Generated by Django 5.0.1 on 2024-01-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0020_auto_20210621_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='additional_images')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_of_user.profile')),
            ],
        ),
    ]
