# Generated by Django 5.0.1 on 2024-01-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0021_additionalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
