# Generated by Django 5.0.1 on 2024-01-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0022_delete_additionalimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='avatar',
        ),
    ]
