# Generated by Django 5.0.1 on 2024-01-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0023_rename_image_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plant_name_1',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='plant_port_1',
            field=models.ImageField(default='default/user.png', upload_to='images'),
        ),
    ]
