# Generated by Django 5.0.1 on 2024-01-31 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0024_profile_plant_name_1_profile_plant_port_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='plant_port_1',
            new_name='plant_image_1',
        ),
    ]
