# Generated by Django 5.0.1 on 2024-02-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0025_rename_plant_port_1_profile_plant_image_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plant_image_1',
            field=models.ImageField(default='', upload_to='additional_images'),
        ),
    ]
