# Generated by Django 5.0.1 on 2024-02-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0026_alter_profile_plant_image_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='temp1',
            field=models.CharField(default='', max_length=19),
        ),
    ]
