# Generated by Django 5.0.1 on 2024-02-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_of_user', '0027_profile_temp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temp1',
        ),
    ]
