name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout the repository
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Log into GHCR
        uses: docker/login-action@v3
        with: 
            registry: ghcr.io
            username: ${{secrets.GH_USERNAME}}
            password: ${{secrets.GH_PAT}}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: Code/.
          push: true
          tags: ghcr.io/ak2466/plantpals:latest
